### ISSUE TITLE
Template and styles for inline oembed videos

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/cwd_base#70]
We're switching from video_embed_field to Drupal core "oembed" functionality for YouTube videos:
https://github.com/CU-CommunityApps/cd_drupal_upstream/issues/42

Accompanying tasks for our Drupal base theme -- can happen any time (no need to wait for the cd_drupal_upstream issue to be complete):
- [ ] Remove extra "div" wrapper from video embed field output:
  - Create `field--field-media-oembed-video.html.twig` -- simply to use `_field--less-wrapped.html.twig` (same as [field--image.html.twig](https://github.com/CU-CommunityApps/cwd_base/blob/d2ca306789b9e46a7978cf452baba9d96307e4d4/templates/media/field--image.html.twig)).
- [ ] Add style rule (including `aspect-ratio` style) for inline video embeds:
```css
iframe.media-oembed-content {
  display: block;
  width: 100%; 
  height: auto;
  aspect-ratio: 16 / 9;
}
```

----

FWIW: This work is already happening on VPUE (as of 2023-09-13, the oembed field template is done, the style rule will be done soon).
